import { GATEQuestion } from './types';

export const GATE_QUESTIONS: GATEQuestion[] = [
  {
    id: 'gate_dfa_01',
    topic: 'Deterministic Finite Automata (DFA)',
    subtopic: 'State Counting & Modulo Arithmetic',
    type: 'NAT',
    difficulty: 'GATE-Level',
    questionText: 'What is the minimum number of states in a minimal DFA accepting the set of all binary strings representing numbers divisible by 5 (expressed in standard binary notation, including e as 0)?',
    natRange: [5, 5],
    correctAnswers: ['5'],
    conceptTested: 'Modulo arithmetic DFA state space cardinality',
    explanation: 'A binary number N mod 5 can have 5 possible remainders: {0, 1, 2, 3, 4}. In standard binary, when a new bit b arrives, the new value becomes (2N + b) mod 5. Each remainder requires a distinct equivalence class (state) in the Myhill-Nerode relation. Thus, exactly 5 states are required and sufficient.',
    gateTrapAlert: 'Trap: Forgetting that the start state is the remainder 0 state and is also the only accepting state.',
    examTip: 'Shortcut: For divisibility by k in base b, if gcd(b, k) = 1, the minimal DFA always has exactly k states.',
    beginnerExplanation: 'Think of 5 buckets for remainders when dividing by 5. Whenever a 0 or 1 is typed, the remainder changes deterministically to a new bucket. You need 5 states for the 5 remainders 0, 1, 2, 3, 4.',
    examShortcut: 'For binary (base 2) mod k, when k is odd (like 5), minimal states = k = 5.',
  },
  {
    id: 'gate_min_02',
    topic: 'DFA Minimization',
    subtopic: 'Myhill-Nerode & Partition Refinement',
    type: 'MCQ',
    difficulty: 'GATE-Trap',
    questionText: 'Consider a DFA M with n states. If we swap the accepting and non-accepting states of M to obtain M\', which of the following is ALWAYS true regarding the minimal number of states of M\'?',
    options: [
      { id: 'A', text: 'Minimal DFA for M\' has fewer states than M' },
      { id: 'B', text: 'Minimal DFA for M\' has exactly the same number of states as the minimal DFA for M' },
      { id: 'C', text: 'Minimal DFA for M\' can have up to 2^n states' },
      { id: 'D', text: 'Minimal DFA for M\' has n - 1 states' },
    ],
    correctAnswers: ['B'],
    conceptTested: 'Complement of Regular Languages and DFA Minimization Isomorphism',
    explanation: 'For a complete DFA M, complementing the language is achieved simply by swapping final and non-final states. Two states p and q are distinguishable in M if and only if they are distinguishable in M\' (by the exact same distinguishing strings). Hence, the equivalence classes under the Myhill-Nerode relation remain identical, meaning the minimal DFA for L\' has the exact same number of states as minimal DFA for L.',
    whyOtherWrong: {
      A: 'Swapping final states does not merge previously distinguishable states.',
      C: 'Complement of a DFA does NOT require subset construction; that is only for NFAs.',
      D: 'There is no decrement in state count for complementation of a deterministic machine.',
    },
    gateTrapAlert: 'Trap: Confusing NFA complementation (which can cause exponential blowup 2^n) with DFA complementation (which preserves exact state count).',
    examTip: 'Key Rule: DFA Complement = Swap Final/Non-Final states -> State count unchanged. NFA Complement = Must convert to DFA first -> Can take up to 2^n states.',
  },
  {
    id: 'gate_nfa_dfa_03',
    topic: 'NFA ? DFA conversion',
    subtopic: 'Worst-case subset explosion',
    type: 'MCQ',
    difficulty: 'GATE-Level',
    questionText: 'Let L_k be the language over {0, 1} consisting of all strings where the k-th symbol from the right is 1. What is the number of states in the minimal NFA and the minimal DFA for L_k, respectively?',
    options: [
      { id: 'A', text: 'NFA: k states, DFA: k states' },
      { id: 'B', text: 'NFA: k + 1 states, DFA: 2^k states' },
      { id: 'C', text: 'NFA: 2^k states, DFA: k + 1 states' },
      { id: 'D', text: 'NFA: k states, DFA: 2^(k-1) states' },
    ],
    correctAnswers: ['B'],
    conceptTested: 'Exponential state gap between NFA and DFA',
    explanation: 'An NFA for L_k only needs k + 1 states: state q0 loops on {0, 1}, on 1 guesses the k-th position, and moves through k deterministic delay states to reach accept state q_k. A DFA, however, must remember the last k bits seen in memory. Since there are 2^k possible suffixes of length k, all 2^k suffixes are pairwise distinguishable by Myhill-Nerode, requiring 2^k DFA states.',
    whyOtherWrong: {
      A: 'A DFA cannot recognize L_k with only k states because it cannot remember k past bits without 2^k states.',
      C: 'Inverted: NFA is concise (k+1 states) while DFA suffers exponential blowup (2^k).',
      D: 'NFA requires k+1 states (start + k steps), DFA requires 2^k states.',
    },
    gateTrapAlert: 'Trap: Assuming DFA can guess like NFA. A DFA must maintain deterministic memory of the entire k-length sliding window.',
    examTip: 'Standard GATE Formula: k-th from right is "1" -> NFA = k + 1 states, DFA = 2^k states.',
  },
  {
    id: 'gate_pumping_04',
    topic: 'Pumping Lemma for Regular Languages',
    subtopic: 'Adversarial Quantifiers',
    type: 'MSQ',
    difficulty: 'GATE-Level',
    questionText: 'Which of the following statements regarding the Pumping Lemma for Regular Languages are TRUE? (Select all that apply)',
    options: [
      { id: 'A', text: 'The Pumping Lemma is a necessary condition for a language to be regular, but NOT a sufficient condition.' },
      { id: 'B', text: 'If a language satisfies the pumping lemma property, it is guaranteed to be regular.' },
      { id: 'C', text: 'The Pumping Lemma cannot be used to prove that a language IS regular.' },
      { id: 'D', text: 'In the decomposition w = xyz, the constraint |xy| = p implies that the pumped portion y must be located within the first p symbols of w.' },
    ],
    correctAnswers: ['A', 'C', 'D'],
    conceptTested: 'Logical quantification and limits of Pumping Lemma',
    explanation: 'The Pumping Lemma states: Regular => Pumping Property holds. By contrapositive: Not Pumping Property => Not Regular. It can only be used as a tool to DISPROVE regularity. There exist non-regular languages that satisfy the pumping condition (e.g. {a^i b^j c^j | i = 1, j = 1} ? {b^j c^k | j, k = 0}). Thus, it is necessary but NOT sufficient.',
    whyOtherWrong: {
      B: 'Pumping lemma is NOT sufficient; satisfying it does not guarantee regularity.',
    },
    gateTrapAlert: 'Common Trap: Trying to use the Pumping Lemma to prove a language is regular. To prove regularity, construct a DFA/NFA/RE or use closure properties!',
    examTip: 'Exam Mantra: Pumping Lemma is a NEGATIVE test only (proves non-regularity by contradiction).',
  },
  {
    id: 'gate_regex_05',
    topic: 'Regular Expressions',
    subtopic: 'Equivalence and Identities',
    type: 'MCQ',
    difficulty: 'Easy',
    questionText: 'Which of the following regular expressions represents the set of all binary strings that DO NOT contain two consecutive 0s (i.e. no substring 00)?',
    options: [
      { id: 'A', text: '(1|01)*(0|e)' },
      { id: 'B', text: '(0|1)*00(0|1)*' },
      { id: 'C', text: '(01|10)*' },
      { id: 'D', text: '(1*01*)*(0|e)' },
    ],
    correctAnswers: ['A'],
    conceptTested: 'Sub-pattern constraints and empty-string handling',
    explanation: 'Any string without 00 can be decomposed into blocks of "1" and "01", ending optionally with a trailing "0". This is represented by (1 | 01)*(0 | e) or (1 | 01)*(e | 0).',
    whyOtherWrong: {
      B: 'This represents strings that DO contain 00 (the exact opposite).',
      C: 'Cannot generate the string "1" or "111", which are valid strings without 00.',
      D: 'Allows generating "00" through nested repetition.',
    },
    gateTrapAlert: 'Trap: Forgetting that a single trailing "0" is allowed after blocks of 1 and 01.',
    examTip: 'Shortcut: Test small strings: e (accept), 0 (accept), 1 (accept), 00 (reject), 010 (accept).',
  },
  {
    id: 'gate_lexer_06',
    topic: 'Lexical Analysis using Finite Automata',
    subtopic: 'Maximal Munch & Conflict Resolution',
    type: 'MCQ',
    difficulty: 'Medium',
    questionText: 'During lexical analysis in a compiler, if the input buffer contains the sequence "ifx", how does a maximal-munch (longest match) lexer with standard C/Java token rules classify it?',
    options: [
      { id: 'A', text: 'KEYWORD "if" followed by IDENTIFIER "x"' },
      { id: 'B', text: 'Single IDENTIFIER "ifx"' },
      { id: 'C', text: 'Lexical syntax error' },
      { id: 'D', text: 'KEYWORD "ifx"' },
    ],
    correctAnswers: ['B'],
    conceptTested: 'Maximal Munch principle in compiler lexical analysis',
    explanation: 'Maximal Munch (Longest Match Rule) dictates that the lexer must continue scanning as long as the DFA can accept a longer prefix. Since "ifx" matches the IDENTIFIER regex [a-zA-Z_][a-zA-Z0-9_]* for 3 characters, while "if" only matches 2 characters, the lexer selects the longer 3-character match "ifx" as a single IDENTIFIER token.',
    whyOtherWrong: {
      A: 'Violates Maximal Munch: the lexer prefers longer valid tokens over shorter keywords.',
      C: '"ifx" is a perfectly valid identifier name.',
      D: '"ifx" is not in the reserved keyword list.',
    },
    gateTrapAlert: 'Trap: Believing keyword priority overrides token length. Priority rule only resolves ties between equal-length token matches!',
    examTip: 'Rule of Thumb in Lexers: 1. Longest Match (Maximal Munch) ALWAYS takes priority. 2. Rule order / Keyword priority is used ONLY to break ties between equal lengths.',
  },
  {
    id: 'gate_equiv_07',
    topic: 'Equivalence of finite automata and regular expressions',
    subtopic: 'GNFA & Arden\'s Theorem',
    type: 'NAT',
    difficulty: 'Medium',
    questionText: 'What is the minimum number of states in a DFA that accepts strings over {a, b} where the number of a\'s is a multiple of 3 AND the number of b\'s is a multiple of 2?',
    natRange: [6, 6],
    correctAnswers: ['6'],
    conceptTested: 'Cross-product construction for intersection of regular languages',
    explanation: 'Let L1 = {w | count(a) mod 3 == 0} (requires 3 states) and L2 = {w | count(b) mod 2 == 0} (requires 2 states). The language L = L1 n L2 is recognized by the product DFA with state space Q1 � Q2. Since gcd(3, 2) = 1 and the conditions track independent alphabets, the minimal DFA has exactly 3 � 2 = 6 states.',
    gateTrapAlert: 'Trap: Adding states 3 + 2 = 5. Independent modular counting across distinct symbols requires the Cartesian product of states (3 � 2 = 6).',
    examTip: 'Formula: (a mod m == 0) AND (b mod n == 0) on alphabet {a, b} requires exactly m � n states.',
  },
  {
    id: 'gate_reg_lang_08',
    topic: 'Regular Languages',
    subtopic: 'Closure Properties',
    type: 'MSQ',
    difficulty: 'GATE-Level',
    questionText: 'Which of the following classes of operations are Regular Languages CLOSED under? (Select all that apply)',
    options: [
      { id: 'A', text: 'Union, Intersection, and Complement' },
      { id: 'B', text: 'Concatenation and Kleene Star' },
      { id: 'C', text: 'Homomorphism and Inverse Homomorphism' },
      { id: 'D', text: 'Infinite Union of regular languages' },
    ],
    correctAnswers: ['A', 'B', 'C'],
    conceptTested: 'Closure properties of Regular Languages',
    explanation: 'Regular languages are a boolean algebra and closed under: Union, Intersection, Complement, Set Difference, Concatenation, Kleene Star, Reversal, Homomorphism, Inverse Homomorphism, and Prefix/Suffix quotient. However, they are NOT closed under INFINITE union (e.g. ?_{n = 0} {a^n b^n} = {a^n b^n | n = 0}, which is non-regular).',
    whyOtherWrong: {
      D: 'Every language is a union of singleton strings (which are regular), so infinite union can generate non-regular or even undecidable languages.',
    },
    gateTrapAlert: 'Trap: Confusing finite union (which preserves regularity) with infinite union (which does NOT).',
    examTip: 'Remember: Regular languages are closed under almost all standard FINITE operations.',
  },
];
