import { PumpingLanguage } from '../types';

export const PUMPING_LANGUAGES: PumpingLanguage[] = [
  {
    id: 'an_bn',
    name: 'L = { anbn | n = 0 }',
    latex: 'L = \\{ a^n b^n \\mid n \\ge 0 \\}',
    description: 'Strings of n a\'s followed by exactly n b\'s over alphabet {a, b}.',
    alphabet: ['a', 'b'],
    isRegular: false,
    defaultP: 3,
    defaultW: 'aaabbb',
    explanation: 'Finite automata have finite states and cannot count an unbounded number of a\'s to match against b\'s.',
    adversaryCases: [
      {
        caseName: 'Case 1: y consists entirely of a\'s (y = a?, 1 = k = p)',
        yConstraint: '|xy| = p forces y to lie entirely within the first p a\'s.',
        chosenI: 0,
        pumpedResult: 'a^(p-k) b^p',
        contradictionReason: 'For i = 0 (pumping down), the string becomes a^(p-k) b^p. The number of a\'s is (p-k) which is strictly less than p (number of b\'s). Since p-k ? p, the pumped string ? L. Contradiction!',
      },
      {
        caseName: 'Case 2: Pumping up with i = 2',
        yConstraint: 'y = a? with k = 1',
        chosenI: 2,
        pumpedResult: 'a^(p+k) b^p',
        contradictionReason: 'For i = 2, xy�z = a^(p+k) b^p. The number of a\'s is (p+k) > p. Number of a\'s ? number of b\'s -> string ? L. Contradiction!',
      },
    ],
  },
  {
    id: 'an_bn_cn',
    name: 'L = { anbncn | n = 0 }',
    latex: 'L = \\{ a^n b^n c^n \\mid n \\ge 0 \\}',
    description: 'Strings of n a\'s followed by n b\'s and n c\'s.',
    alphabet: ['a', 'b', 'c'],
    isRegular: false,
    defaultP: 3,
    defaultW: 'aaabbbccc',
    explanation: 'Requires matching three separate unbounded block counts, violating regular pumping and context-free pumping.',
    adversaryCases: [
      {
        caseName: 'Adversary puts y in first p symbols (all a\'s)',
        yConstraint: 'Since |xy| = p, y = a? for 1 = k = p.',
        chosenI: 0,
        pumpedResult: 'a^(p-k) b^p c^p',
        contradictionReason: 'For i = 0, count of a\'s drops to p-k, while counts of b and c remain p. String ? L. Contradiction!',
      },
    ],
  },
  {
    id: 'ww_repeat',
    name: 'L = { ww | w ? {0, 1}* }',
    latex: 'L = \\{ ww \\mid w \\in \\{0, 1\\}^* \\}',
    description: 'Strings formed by repeating any binary word twice (e.g. 0101, 110110).',
    alphabet: ['0', '1'],
    isRegular: false,
    defaultP: 3,
    defaultW: '00010001',
    explanation: 'Recognizing arbitrary copy-repetition requires infinite memory to store and verify the entire first half against the second half.',
    adversaryCases: [
      {
        caseName: 'Adversary splits w = 0? 1 0? 1',
        yConstraint: '|xy| = p means y = 0? (1 = k = p) in the first block of 0\'s.',
        chosenI: 2,
        pumpedResult: '0^(p+k) 1 0^p 1',
        contradictionReason: 'For i = 2, xy�z = 0^(p+k) 1 0^p 1. The midpoint splits the 1s unevenly; the string cannot be factored into two identical halves. Contradiction!',
      },
    ],
  },
  {
    id: '0n_1n',
    name: 'L = { 0n1n | n = 0 }',
    latex: 'L = \\{ 0^n 1^n \\mid n \\ge 0 \\}',
    description: 'Equal number of 0s followed by equal number of 1s.',
    alphabet: ['0', '1'],
    isRegular: false,
    defaultP: 4,
    defaultW: '00001111',
    explanation: 'Standard binary representation of matching counts.',
    adversaryCases: [
      {
        caseName: 'y lies in 0-block: y = 0? (k = 1)',
        yConstraint: '|xy| = p',
        chosenI: 0,
        pumpedResult: '0^(p-k) 1^p',
        contradictionReason: 'For i = 0, count of 0s is p-k < p. Number of 0s does not equal number of 1s. String ? L. Contradiction!',
      },
    ],
  },
  {
    id: 'prime_powers',
    name: 'L = { 1? | p is prime }',
    latex: 'L = \\{ 1^p \\mid p \\text{ is prime} \\}',
    description: 'Unary strings whose length is a prime number.',
    alphabet: ['1'],
    isRegular: false,
    defaultP: 3,
    defaultW: '111',
    explanation: 'Prime numbers grow with non-constant gaps and cannot be captured by periodic cycles in finite state machines.',
    adversaryCases: [
      {
        caseName: 'Choose prime p = pumping length. String w = 1?.',
        yConstraint: '|y| = k = 1, |xy| = p.',
        chosenI: 'p + 1',
        pumpedResult: '1^(p + k�p) = 1^(p(1 + k))',
        contradictionReason: 'For i = p + 1, length of xy^(p+1)z is |w| + p�|y| = p + p�k = p(1 + k), which is composite (divisible by p). Hence string ? L. Contradiction!',
      } as any,
    ],
  },
];
